{
 "title": "RequestRate",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "helloworld.HelloWorldController.HELLO_WORD_METHOD-Time.m1_rate"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(helloworld.HelloWorldController.HELLO_WORD_METHOD-Meter.m1_rate, 'Request_Rate')"
    },
    {}
   ]
  },
  {
   "title": "ErrorRate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(helloworld.HelloWorldController.HELLO_WORD_METHOD_2-Exception.m1_rate, 'errorRate')"
    }
   ]
  },
  {
   "title": "RetryCount",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(helloworld.HelloWorldController.METHOD3_INTERNAL_RETRY_COUNT-Meter.m1_rate, 'retryCount')"
    }
   ]
  },
  {
   "title": "LatencyForRetriedMethods",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "MaxTime (ms)" }
   ],
   "targets": [
    {
     "target": "alias(helloworld.HelloWorldController.METHOD3_INTERNAL_RETRY_COUNT-Time.max, 'retryLatency')"
    }
   ]
  }
 ]
}